### PR TITLE
fix for HTTP Error 403

### PR DESCRIPTION
**Pull request by sackh**
fix for issue #18

### CODE REVIEW

**Comment by deeplook** [comment]
Does it really have to be Windows in the user agent?

**Comment by sackh** [comment]
No windows is not mandatory. below is another example:
` {'User-Agent': 'Mozilla / 5.0 (X11 Linux x86_64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 52.0.2743.116 Safari / 537.36'}`

Let me know which one do you prefer, so I will make change accordingly.

**Comment by deeplook** [comment]
Then let’s not pretend to favour Windows. Otherwise fine.

**Comment by sackh** [comment]
@deeplook - Done

**Review by deeplook — APPROVED** [review]

**Pull request merged**
